### ISSUE TITLE
Support for uuid seams broken.

### ISSUE THREAD

**Issue by Superhepper** [dylanmckay/protocol#20]
I am having issues with getting the feature to use Uuid to work.

Cargo.toml:
```
[dependencies]
protocol-derive = "3.1.3"
protocol= { version = "3.1.3", features = ["uuid"] }
uuid="0.8.1"
```

Trying to compile something simple as

```rust
use uuid::Uuid;
use protocol_derive::Protocol;

#[derive(Protocol, Debug, Copy, Clone, PartialEq, Eq)]
pub struct Foo {
    pub id: Uuid,
}
```

And then I got a compiler error:
```
#[derive(Protocol, Debug, Copy, Clone, PartialEq, Eq)]
|        ^^^^^^^^ the trait `id::__impl_protocol___Parcel_FOR_Foo::protocol::HighLevel` is not implemented for `uuid::Uuid`
```

Am I missing something?

**Comment by dylanmckay** [comment]
I managed to reproduce this - it is fixed in [release 3.1.5](https://crates.io/crates/protocol/3.1.5).

**Comment by dylanmckay** [comment]
I'm going to close this for now but feel free to re-open if the issue persists.

**Comment by Superhepper** [comment]
I have tested it and it compiles now. Thank you!
